# Generated by Django 2.1.5 on 2019-03-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0001_initial'),
        ('empresas', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficioExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=None, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=None, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('remuneracion_min', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('remuneracion_max', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('resumen', models.TextField(blank=True, default=None, null=True)),
                ('estado_oportunidad', models.CharField(blank=True, choices=[('P', 'Archivado'), ('A', 'Abierto'), ('C', 'Cerrado')], default=None, max_length=1, null=True)),
                ('experiencia', models.CharField(blank=True, choices=[('', 'Año'), ('0', 'sin experiencia'), ('1', 'hasta 1 año'), ('2', 'desde 2años'), ('3', 'desde 3años'), ('4', 'desde 4años'), ('5', 'desde 5años'), ('6', 'desde 6años'), ('7', 'desde 7años'), ('8', 'desde 8años'), ('9', 'desde 9años'), ('10', 'desde 10años')], default=None, max_length=1, null=True)),
                ('direccion_map', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('longitud', models.FloatField(blank=True, default=None, null=True, verbose_name='longitud')),
                ('latitud', models.FloatField(blank=True, default=None, null=True, verbose_name='latitud')),
                ('fecha_publicacion', models.DateField(blank=True, default=None, null=True)),
                ('fecha_cese', models.DateField(blank=True, default=None, null=True)),
                ('edad_desde', models.IntegerField(blank=True, default=None, null=True)),
                ('numero_vacantes', models.IntegerField(blank=True, default=None, null=True)),
                ('edad_hasta', models.IntegerField(blank=True, default=None, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='', max_length=1, null=True)),
                ('usuario_creacion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=None, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=None, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('notificacion_enviada', models.BooleanField(default=False, verbose_name='Notificacion enviada')),
                ('url_imagen_empresa_correo', models.URLField(blank=True, default=None, null=True)),
                ('area_experiencia', models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='main.AreaExpeiencia')),
                ('beneficio', models.ManyToManyField(blank=True, default=None, to='main.Beneficio', verbose_name='Beneficios')),
                ('carga_horaria', models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='main.CargaHoraria', verbose_name='Jornada Laboral')),
                ('carrera', models.ManyToManyField(blank=True, default=None, to='main.Carrera', verbose_name='carrera')),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=True, to='main.Ciudad')),
                ('conocimiento', models.ManyToManyField(blank=True, default=None, to='main.Conocimiento', verbose_name='Conocimiento')),
                ('division', models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='empresas.EmpresaDivision')),
                ('empresa', models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='empresas.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='OportunidadCompatibilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibilidad_academica', models.IntegerField(blank=True, default=0, null=True)),
                ('compatibilidad_cultural', models.IntegerField(blank=True, default=0, null=True)),
                ('compatibilidad_promedio', models.IntegerField(blank=True, default=0, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=None, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=None, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
                ('estudiante', models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='estudiante.Estudiante')),
                ('oportunidad', models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='oportunidades.Oportunidad')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PesoCompatibilidadOportunidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rama_carrera', models.FloatField(blank=True, default=None, null=True)),
                ('universidad', models.FloatField(blank=True, default=None, null=True)),
                ('grado_estudio', models.FloatField(blank=True, default=None, null=True)),
                ('periodo_graduacion', models.FloatField(blank=True, default=None, null=True)),
                ('edad', models.FloatField(blank=True, default=None, null=True)),
                ('ubicacion', models.FloatField(blank=True, default=None, null=True)),
                ('genero', models.FloatField(blank=True, default=None, null=True)),
                ('tipo_puesto', models.FloatField(blank=True, default=None, null=True)),
                ('carga_horaria', models.FloatField(blank=True, default=None, null=True)),
                ('remuneracion', models.FloatField(blank=True, default=None, null=True)),
                ('idioma', models.FloatField(blank=True, default=None, null=True)),
                ('conocimiento', models.FloatField(blank=True, default=None, null=True)),
                ('area_experiencia', models.FloatField(blank=True, default=None, null=True)),
                ('tiempo_experiencia', models.FloatField(blank=True, default=None, null=True)),
                ('ciclo_actual', models.FloatField(blank=True, default=None, null=True)),
                ('experiencia', models.FloatField(blank=True, default=None, null=True)),
                ('usuario_creacion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=None, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=None, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_postulacion', models.CharField(blank=True, choices=[('P', 'Postulacion'), ('E', 'En Evaluacion'), ('F', 'Finalizado')], default='A', max_length=1, null=True)),
                ('estado_fase', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
                ('calificacion', models.CharField(blank=True, choices=[('SC', 'Sin Calificar'), ('B', 'Bueno'), ('MB', 'Muy Bueno'), ('R', 'Regular')], default='SC', max_length=2, null=True)),
                ('usuario_creacion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=None, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=None, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
                ('visto', models.BooleanField(default=False, verbose_name='Postulacion Vista')),
                ('estudiante', models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='estudiante.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='ProcesoCompatibilidadOportunidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procesar', models.BooleanField(blank=True, default=False, verbose_name='Seleccione y guarde para procesar la compatibilidad de todas las oportunidades')),
            ],
        ),
        migrations.CreateModel(
            name='ProcesoFase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('orden', models.IntegerField(blank=True, default=None, null=True)),
                ('mensaje_contenido', models.TextField(blank=True, default=None, null=True)),
                ('mensaje_asunto', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('usuario_creacion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=None, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=None, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='postulacion',
            name='fase',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='oportunidades.ProcesoFase'),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='oportunidad',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='oportunidades.Oportunidad'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='fase',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='oportunidades.ProcesoFase'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='grado_estudio',
            field=models.ManyToManyField(blank=True, default=None, to='main.GradoEstudio', verbose_name='grado estudios'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='graduacion_desde',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=True, related_name='graduacion_desde', to='main.PeriodosGraduacion'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='graduacion_hasta',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=True, related_name='graduacion_hasta', to='main.PeriodosGraduacion'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='idioma',
            field=models.ManyToManyField(blank=True, default=None, to='main.Idioma', verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='nivel_academico',
            field=models.ManyToManyField(blank=True, default=None, to='main.NivelAcademico', verbose_name='nivel academico'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, to='main.Pais'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='rama_carrera',
            field=models.ManyToManyField(blank=True, default=None, to='main.RamaCarrera', verbose_name='rama carrera'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='remuneracion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='main.TipoRemuneracion', verbose_name='Tipo de Remuneracion'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='tiempo_experiencia',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='main.TiempoExpeiencia'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='tipo_carrera',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='main.TipoCarrera'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='tipo_puesto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='main.TipoPuesto', verbose_name='Tipo Puesto'),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='universidad',
            field=models.ManyToManyField(blank=True, default=None, to='main.Universidad', verbose_name='universidad'),
        ),
        migrations.AddField(
            model_name='beneficioextra',
            name='oportunidad',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='oportunidades.Oportunidad'),
        ),
    ]
