# Generated by Django 2.1.5 on 2019-03-02 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidad',
            name='area_experiencia',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.AreaExpeiencia'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Ciudad'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='division',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.EmpresaDivision'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='empresa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresa'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='fase',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='oportunidades.ProcesoFase'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='graduacion_desde',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graduacion_desde', to='main.PeriodosGraduacion'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='graduacion_hasta',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graduacion_hasta', to='main.PeriodosGraduacion'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Pais'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='remuneracion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.TipoRemuneracion', verbose_name='Tipo de Remuneracion'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='tiempo_experiencia',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.TiempoExpeiencia'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='tipo_carrera',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.TipoCarrera'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='tipo_puesto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.TipoPuesto', verbose_name='Tipo Puesto'),
        ),
        migrations.AlterField(
            model_name='oportunidadcompatibilidad',
            name='estudiante',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante'),
        ),
        migrations.AlterField(
            model_name='oportunidadcompatibilidad',
            name='oportunidad',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='oportunidades.Oportunidad'),
        ),
    ]
