# Generated by Django 2.1.5 on 2019-02-19 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0002_postulacion_estudiante_calificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulacion',
            name='estudiante_calificacion',
        ),
    ]
