# Generated by Django 2.1.5 on 2019-03-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0002_auto_20190302_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidad',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default=None, max_length=1, null=True),
        ),
    ]
