# Generated by Django 2.1.5 on 2019-03-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0003_auto_20190304_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidad',
            name='titulo',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
