# Generated by Django 2.1.5 on 2019-02-19 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0004_postulacion_estudiante_calificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulacion',
            old_name='estudiante_calificacion',
            new_name='calificacion',
        ),
    ]
