# Generated by Django 2.1.5 on 2019-03-04 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0004_auto_20190304_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidad',
            name='grado_estudio',
            field=models.ManyToManyField(default=None, to='main.GradoEstudio', verbose_name='grado estudios'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='rama_carrera',
            field=models.ManyToManyField(default=None, to='main.RamaCarrera', verbose_name='rama carrera'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='resumen',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='tipo_puesto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.TipoPuesto', verbose_name='Tipo Puesto'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='titulo',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
