# Generated by Django 2.1.5 on 2019-02-20 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0005_auto_20190219_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulacion',
            name='calificacion',
        ),
    ]
