# Generated by Django 2.1.5 on 2019-03-15 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0006_oportunidad_distrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oportunidad',
            name='distrito',
        ),
    ]
