# Generated by Django 2.1.5 on 2019-02-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0007_postulacion_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidad',
            name='carga_horaria',
            field=models.CharField(blank=True, choices=[('PT', 'Part time'), ('FT', 'Full time')], default=None, max_length=2, null=True, verbose_name='Jornada Laboral'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='remuneracion',
            field=models.CharField(blank=True, choices=[('F', 'Fijo'), ('I', 'Intervalo')], default=None, max_length=1, null=True, verbose_name='Remuneracion'),
        ),
    ]
