# Generated by Django 2.1.5 on 2019-02-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oportunidades', '0008_auto_20190220_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oportunidad',
            name='remuneracion',
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='remuneracion_fija',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='tipo_remuneracion',
            field=models.CharField(blank=True, choices=[('F', 'Fijo'), ('I', 'Intervalo')], default=None, max_length=1, null=True, verbose_name='Tipo de Remuneracion'),
        ),
    ]
