# Generated by Django 2.1.5 on 2019-02-11 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('descripcion', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('quienes_somos', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('telefono', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('RUC', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('ano_fundacion', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('website', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d', verbose_name='logo')),
                ('direccion_map', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('longitud', models.FloatField(blank=True, default=None, null=True, verbose_name='longitud')),
                ('latitud', models.FloatField(blank=True, default=None, null=True, verbose_name='latitud')),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('usuario_creacion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_activacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
                ('ciudad', models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='main.Ciudad')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='FacturacionAnual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, default='A', max_length=1, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'FacturacionAnual',
                'verbose_name_plural': 'FacturacionesAnuales',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='NumeroFuncionarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, default='A', max_length=1, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'NumeroFuncionario',
                'verbose_name_plural': 'NumeroFuncionarios',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrador', models.BooleanField(blank=True, default=False)),
                ('usuario_broder', models.BooleanField(blank=True, default=False)),
                ('usuario_creacion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('fecha_activacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('usuario_modificacion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
                ('empresa', models.ForeignKey(on_delete=True, to='empresas.Empresa')),
                ('persona', models.OneToOneField(on_delete=True, to='main.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, default='A', max_length=1, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'ordering': ['descripcion'],
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='facturacion_anual',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='empresas.FacturacionAnual'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='numero_funcionarios',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='empresas.NumeroFuncionarios'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='pais',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='main.Pais'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sector',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='empresas.Sector'),
        ),
    ]
