# Generated by Django 2.1.5 on 2019-03-02 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='ciudad',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Ciudad'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='facturacion_anual',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.FacturacionAnual'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='numero_funcionarios',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.NumeroFuncionarios'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='pais',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Pais'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='sector',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Sector'),
        ),
        migrations.AlterField(
            model_name='empresadivision',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresa'),
        ),
        migrations.AlterField(
            model_name='representante',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresa'),
        ),
        migrations.AlterField(
            model_name='representante',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Persona'),
        ),
    ]
