# Generated by Django 2.1.5 on 2019-02-14 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20190213_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
