# Generated by Django 2.1.5 on 2019-02-23 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_empresadivision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='logo',
        ),
    ]
