# Generated by Django 2.1.5 on 2019-03-02 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadesExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, default=None, null=True)),
                ('organizacion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConocimientoExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera_referencial', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('semestre_actual', models.CharField(blank=True, choices=[('1', 'Ciclo 1'), ('2', 'Ciclo 2'), ('3', 'Ciclo 3'), ('4', 'Ciclo 4'), ('5', 'Ciclo 5'), ('6', 'Ciclo 6'), ('7', 'Ciclo 7'), ('8', 'Ciclo 8'), ('9', 'Ciclo 9'), ('10', 'Ciclo 10')], default=None, max_length=2, null=True)),
                ('semestre_inicio_estudio', models.CharField(blank=True, choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Setiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], default=None, max_length=2, null=True)),
                ('ano_inicio_estudio', models.CharField(blank=True, choices=[('', 'Año'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028')], default=None, max_length=4, null=True)),
                ('semestre_graduacion', models.CharField(blank=True, choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Setiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], default=None, max_length=2, null=True)),
                ('ano_graduacion', models.CharField(blank=True, choices=[('', 'Año'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028')], default=None, max_length=4, null=True)),
                ('remuneracion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img/%Y/%m/%d', verbose_name='foto perfil')),
                ('foto_facebook_url', models.URLField(blank=True, default=None, null=True)),
                ('completo_test', models.BooleanField(default=False)),
                ('correo_registro', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
                ('enviado_correo_cargararea', models.BooleanField(default=False)),
                ('carga_horaria', models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='main.CargaHoraria')),
                ('carrera', models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='main.Carrera')),
                ('ciudad', models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='main.Ciudad')),
                ('conocimiento', models.ManyToManyField(blank=True, default=None, to='main.Conocimiento', verbose_name='Conocimiento')),
                ('distrito', models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='main.Distrito')),
                ('grado_estudio', models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='main.GradoEstudio')),
                ('idioma', models.ManyToManyField(blank=True, default=None, to='main.Idioma', verbose_name='Idioma')),
                ('nivel_academico', models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='main.NivelAcademico')),
                ('pais', models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='main.Pais')),
                ('persona', models.OneToOneField(on_delete=True, to='main.Persona')),
                ('tipo_puesto', models.ManyToManyField(blank=True, default=None, to='main.TipoPuesto', verbose_name='Tipo Puesto')),
                ('universidad', models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='main.Universidad')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaProfesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto_referencial', models.CharField(default=None, max_length=50, null=True)),
                ('empresa_referencial', models.CharField(default=None, max_length=50, null=True)),
                ('fecha_desde', models.DateField(blank=True, default=None, null=True)),
                ('fecha_hasta', models.DateField(blank=True, default=None, null=True)),
                ('trabajo_actual', models.CharField(default='N', max_length=1)),
                ('descripcion', models.TextField(blank=True, default=None, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
                ('area_experiencia', models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='main.AreaExpeiencia')),
                ('empresa', models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='empresas.Empresa')),
                ('estudiante', models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='estudiante.Estudiante')),
                ('puesto', models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='empresas.Puesto')),
            ],
        ),
        migrations.CreateModel(
            name='Resumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, default=None, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
                ('estudiante', models.ForeignKey(on_delete=True, to='estudiante.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Voluntariado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('organizacion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('fecha_desde', models.DateField(null=True)),
                ('fecha_hasta', models.DateField(blank=True, default=None, null=True)),
                ('voluntariado_actual', models.CharField(default='N', max_length=1)),
                ('descripcion', models.TextField(blank=True, default=None, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
                ('estudiante', models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='estudiante.Estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='conocimientoextra',
            name='estudiante',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='estudiante.Estudiante'),
        ),
        migrations.AddField(
            model_name='actividadesextra',
            name='estudiante',
            field=models.ForeignKey(on_delete=True, to='estudiante.Estudiante'),
        ),
    ]
