# Generated by Django 2.1.5 on 2019-03-02 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadesextra',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante'),
        ),
        migrations.AlterField(
            model_name='conocimientoextra',
            name='estudiante',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='carga_horaria',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CargaHoraria'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='carrera',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Carrera'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='ciudad',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Ciudad'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='distrito',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Distrito'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='grado_estudio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.GradoEstudio'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nivel_academico',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.NivelAcademico'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='pais',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Pais'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Persona'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='universidad',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Universidad'),
        ),
        migrations.AlterField(
            model_name='experienciaprofesional',
            name='area_experiencia',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.AreaExpeiencia'),
        ),
        migrations.AlterField(
            model_name='experienciaprofesional',
            name='empresa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresa'),
        ),
        migrations.AlterField(
            model_name='experienciaprofesional',
            name='estudiante',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante'),
        ),
        migrations.AlterField(
            model_name='experienciaprofesional',
            name='puesto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Puesto'),
        ),
        migrations.AlterField(
            model_name='resumen',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante'),
        ),
        migrations.AlterField(
            model_name='voluntariado',
            name='estudiante',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante'),
        ),
    ]
