# Generated by Django 2.1.5 on 2019-02-18 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='calificacion',
        ),
    ]
