# Generated by Django 2.1.5 on 2019-03-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0002_auto_20190302_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='tiempo_experiencia',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
