# Generated by Django 2.1.5 on 2019-02-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0003_estudiante_estudiante_calificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='estudiante_calificacion',
            new_name='calificacion',
        ),
    ]
