# Generated by Django 2.1.5 on 2019-02-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0005_remove_estudiante_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='calificacion',
            field=models.CharField(blank=True, choices=[('SC', 'Sin Calificar'), ('B', 'Bueno'), ('MB', 'Muy Bueno'), ('R', 'Regular')], default='SC', max_length=2, null=True),
        ),
    ]
