# Generated by Django 2.1.5 on 2019-02-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0006_estudiante_calificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='calificacion',
        ),
    ]
