# Generated by Django 2.1.5 on 2019-02-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0007_remove_estudiante_calificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='carga_horaria',
            field=models.CharField(blank=True, choices=[('PT', 'Part time'), ('FT', 'Full time')], default=None, max_length=2, null=True, verbose_name='Jornada Laboral'),
        ),
    ]
