# Generated by Django 2.1.5 on 2019-03-02 05:22

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaExpeiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
            ],
            options={
                'ordering': ['orden', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CargaHoraria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
                ('codigo_externo', models.CharField(blank=True, default=None, max_length=20, null=True)),
            ],
            options={
                'ordering': ['orden', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, default='A', max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Conocimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
                ('ciudad', models.ForeignKey(on_delete=True, to='main.Ciudad')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='GradoEstudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='IdiomaBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='NivelAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, default='A', max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PeriodosGraduacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('secuencia_universitaria', models.IntegerField(blank=True, null=True)),
                ('secuencia_tecnica', models.IntegerField(blank=True, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, default=None, null=True)),
                ('tipo_persona', models.CharField(default='E', max_length=1)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='', max_length=1, null=True)),
                ('dni', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('enviar_correo', models.BooleanField(blank=True, default=False)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
                ('usuario', models.OneToOneField(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['usuario'],
            },
        ),
        migrations.CreateModel(
            name='RamaCarrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='TiempoExpeiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('meses_tope', models.IntegerField(blank=True, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
            ],
            options={
                'ordering': ['orden', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoCarrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('total_ciclos', models.IntegerField(blank=True, null=True, verbose_name='total de ciclos')),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
            ],
            options={
                'ordering': ['orden', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoPuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
            ],
            options={
                'ordering': ['orden', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoRemuneracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('nemonico', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
                ('pais', models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='main.Pais')),
                ('tipo_carrera', models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='main.TipoCarrera')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='idioma',
            name='idiomabase',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='main.IdiomaBase'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(on_delete=True, to='main.Pais'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='rama_carrera',
            field=models.ManyToManyField(blank=True, default=None, to='main.RamaCarrera'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='tipo_carrera',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=True, to='main.TipoCarrera'),
        ),
    ]
