# Generated by Django 2.1.5 on 2019-02-11 19:15

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, default='A', max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, default='A', max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, default=None, null=True)),
                ('tipo_persona', models.CharField(default='E', max_length=1)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='', max_length=1, null=True)),
                ('dni', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('enviar_correo', models.BooleanField(blank=True, default=False)),
                ('fecha_activacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_creacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('fecha_modificacion', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivado')], default='A', max_length=1, null=True)),
                ('usuario', models.OneToOneField(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['usuario'],
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(on_delete=True, to='main.Pais'),
        ),
    ]
